// Build-time cartographic plate generator for the Contact "base of operations"
// map. Run once with `node scripts/make-map.mjs`; commit the script AND the
// generated src/components/contact/world-map.ts. Nothing in src/ imports d3-geo,
// topojson-client, or world-atlas at runtime — they exist only for this script.
//
// The output is a cropped orthographic globe centred so East Africa → Japan
// arcs across the frame, with Sri Lanka carried at higher resolution so its
// teardrop reads.

import { createRequire } from "node:module";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { geoOrthographic, geoPath } from "d3-geo";
import * as topojson from "topojson-client";

// Bare JSON imports (`import x from "…json"`) are gated behind import assertions
// that differ across Node versions — resolve + read + parse is portable.
const require = createRequire(import.meta.url);
const topo110 = JSON.parse(
  readFileSync(require.resolve("world-atlas/countries-110m.json"), "utf8")
);
const topo50 = JSON.parse(
  readFileSync(require.resolve("world-atlas/countries-50m.json"), "utf8")
);

const VIEWBOX = "0 0 1600 900";

// Validated framing — do not re-tune. The translate-y (620) sits below the
// frame centre (450) so the sphere edge clips only the top corners while the
// bottom corners stay on the globe. Sri Lanka lands near horizontal centre,
// ~78% down; Nairobi → Mumbai → Tokyo sweeps across the plate.
const projection = geoOrthographic()
  .rotate([-80, -12])
  .scale(920)
  .translate([800, 620]);

// digits(1) trims coordinate precision — no visible difference at plate scale,
// meaningfully smaller path strings.
const path = geoPath(projection).digits(1);

// Land: merge every 110m country EXCEPT Sri Lanka into a single MultiPolygon so
// shared borders dissolve (concatenating per-country paths would double-draw
// every border and bloat the file). 110m only — the 50m merged land is ~515 KB,
// 4× budget.
const landGeometries = topo110.objects.countries.geometries.filter(
  (g) => g.properties.name !== "Sri Lanka"
);
const landMerged = topojson.merge(topo110, landGeometries);
const land = path(landMerged);

// Sri Lanka ALWAYS from 50m: at 110m it is a 10-point blob missing Jaffna; at
// 50m it is the recognisable 92-point teardrop (~1.4 KB). Match by name — ids
// are STRINGS ("144"), a numeric compare silently matches nothing, and some
// geometries carry no id at all.
const lankaGeom = topo50.objects.countries.geometries.find(
  (g) => g.properties.name === "Sri Lanka"
);
if (!lankaGeom) throw new Error("Sri Lanka geometry not found in countries-50m.json");
const lankaFeature = topojson.feature(topo50, lankaGeom);
const lanka = path(lankaFeature);

const sphere = path({ type: "Sphere" });

// Projected pixel position of Sri Lanka's centre, for the radar pulse + label.
const lankaPoint = projection([79.92, 7.03]).map((n) => Math.round(n * 10) / 10);

const banner = "// AUTO-GENERATED by scripts/make-map.mjs — do not edit by hand.\n// Cropped orthographic plate: land silhouettes + Sri Lanka highlight.\n";

const out =
  banner +
  `export const viewBox = ${JSON.stringify(VIEWBOX)};\n` +
  `export const lankaPoint: [number, number] = [${lankaPoint[0]}, ${lankaPoint[1]}];\n` +
  `export const sphere = ${JSON.stringify(sphere)};\n` +
  `export const land = ${JSON.stringify(land)};\n` +
  `export const lanka = ${JSON.stringify(lanka)};\n`;

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, "../src/components/contact/world-map.ts");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out, "utf8");

const kb = (s) => (Buffer.byteLength(s, "utf8") / 1024).toFixed(1);
console.log(`wrote ${outPath}`);
console.log(`  total   ${kb(out)} KB`);
console.log(`  land    ${kb(land)} KB`);
console.log(`  lanka   ${kb(lanka)} KB`);
console.log(`  sphere  ${kb(sphere)} KB`);
console.log(`  lankaPoint  [${lankaPoint[0]}, ${lankaPoint[1]}]`);
